export const APP = {
  UPDATE_LOADING: "APP_UPDATE_LOADING",
  UPDATE_ERROR: "APP_UPDATE_ERROR",
  OPTIONS_REQUEST: "APP_OPTIONS_REQUEST",
  OPTIONS_SUCCESS: "APP_OPTIONS_SUCCESS",
}

export default {
  APP,
}
