export const APP = {
  UPDATE_LOADING: "APP_UPDATE_LOADING",
  UPDATE_ERROR: "APP_UPDATE_ERROR",
  OPTIONS_REQUEST: "APP_OPTIONS_REQUEST",
  OPTIONS_SUCCESS: "APP_OPTIONS_SUCCESS",
  SET_UP_UPDATE_REQUEST: "SET_UP_UPDATE_REQUEST",
  SET_UP_UPDATE_SUCCESS: "SET_UP_UPDATE_SUCCESS",
  OPTION_UPDATE_REQUEST: "OPTION_UPDATE_REQUEST",
  OPTION_UPDATE_SUCCESS: "OPTION_UPDATE_SUCCESS",
}

export default {
  APP,
}
